"""add max_steps order_index divergence_step actual_response

Revision ID: 019792725a23
Revises: 4fc29344078d
Create Date: 2026-06-06 16:01:03.251194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '019792725a23'
down_revision: Union[str, Sequence[str], None] = '4fc29344078d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('max_steps', sa.Integer(), nullable=True))
    op.add_column('test_cases', sa.Column('order_index', sa.Integer(), nullable=True))
    op.add_column('test_results', sa.Column('actual_response', sa.Text(), nullable=True))
    op.add_column('test_results', sa.Column('divergence_step', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_results', 'divergence_step')
    op.drop_column('test_results', 'actual_response')
    op.drop_column('test_cases', 'order_index')
    op.drop_column('test_cases', 'max_steps')
    # ### end Alembic commands ###
