"""multi-model support + replay mode

Revision ID: 4fc29344078d
Revises: 
Create Date: 2026-06-06 15:38:16.507727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc29344078d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_suites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_model_type', sa.String(length=64), nullable=True),
    sa.Column('multi_model_test', sa.Boolean(), nullable=False),
    sa.Column('models_to_test', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('suite_id', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(length=64), nullable=False),
    sa.Column('model_display_name', sa.String(length=128), nullable=True),
    sa.Column('multi_model_test', sa.Boolean(), nullable=False),
    sa.Column('models_to_test', sa.JSON(), nullable=True),
    sa.Column('parent_run_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=True),
    sa.Column('fail_count', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('execution_trace_replay', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('suite_id', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.Column('expected_tools', sa.JSON(), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('golden_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('test_case_id', sa.String(), nullable=False),
    sa.Column('model_used', sa.String(length=64), nullable=False),
    sa.Column('final_response', sa.Text(), nullable=False),
    sa.Column('execution_trace', sa.JSON(), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('assertion_details', sa.JSON(), nullable=True),
    sa.Column('semantic_score', sa.Float(), nullable=True),
    sa.Column('judge_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_results')
    op.drop_table('test_cases')
    op.drop_table('runs')
    op.drop_table('test_suites')
    # ### end Alembic commands ###
